/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as R500RouteImport } from './routes/500'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as TagsTagRouteImport } from './routes/tags/$tag'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RssXmlRouteImport } from './routes/rss.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as LlmsTxtRouteImport } from './routes/llms.txt'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LocaleProjectsIndexRouteImport } from './routes/$locale/projects/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as LocaleProjectsSlugRouteImport } from './routes/$locale/projects/$slug'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'

const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssXmlRoute = RssXmlRouteImport.update({
  id: '/rss/xml',
  path: '/rss/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsTxtRoute = LlmsTxtRouteImport.update({
  id: '/llms/txt',
  path: '/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProjectsIndexRoute = LocaleProjectsIndexRouteImport.update({
  id: '/$locale/projects/',
  path: '/$locale/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/$locale/blog/',
  path: '/$locale/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProjectsSlugRoute = LocaleProjectsSlugRouteImport.update({
  id: '/$locale/projects/$slug',
  path: '/$locale/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$locale/blog/$slug',
  path: '/$locale/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/archive': typeof ArchiveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tags/$tag': typeof TagsTagRoute
  '/$locale/': typeof LocaleIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/archive': typeof ArchiveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tags/$tag': typeof TagsTagRoute
  '/$locale': typeof LocaleIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tags': typeof TagsIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/projects': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/archive': typeof ArchiveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tags/$tag': typeof TagsTagRoute
  '/$locale/': typeof LocaleIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/archive'
    | '/blog/$slug'
    | '/llms/txt'
    | '/projects/$slug'
    | '/robots/txt'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/tags/$tag'
    | '/$locale/'
    | '/blog/'
    | '/projects/'
    | '/tags/'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/$locale/blog/'
    | '/$locale/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/archive'
    | '/blog/$slug'
    | '/llms/txt'
    | '/projects/$slug'
    | '/robots/txt'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/tags/$tag'
    | '/$locale'
    | '/blog'
    | '/projects'
    | '/tags'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/$locale/blog'
    | '/$locale/projects'
  id:
    | '__root__'
    | '/'
    | '/500'
    | '/archive'
    | '/blog/$slug'
    | '/llms/txt'
    | '/projects/$slug'
    | '/robots/txt'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/tags/$tag'
    | '/$locale/'
    | '/blog/'
    | '/projects/'
    | '/tags/'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/$locale/blog/'
    | '/$locale/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R500Route: typeof R500Route
  ArchiveRoute: typeof ArchiveRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LlmsTxtRoute: typeof LlmsTxtRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  RssXmlRoute: typeof RssXmlRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  TagsTagRoute: typeof TagsTagRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleProjectsSlugRoute: typeof LocaleProjectsSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleProjectsIndexRoute: typeof LocaleProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/xml': {
      id: '/rss/xml'
      path: '/rss/xml'
      fullPath: '/rss/xml'
      preLoaderRoute: typeof RssXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/txt': {
      id: '/llms/txt'
      path: '/llms/txt'
      fullPath: '/llms/txt'
      preLoaderRoute: typeof LlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/projects/': {
      id: '/$locale/projects/'
      path: '/$locale/projects'
      fullPath: '/$locale/projects/'
      preLoaderRoute: typeof LocaleProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/$locale/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/projects/$slug': {
      id: '/$locale/projects/$slug'
      path: '/$locale/projects/$slug'
      fullPath: '/$locale/projects/$slug'
      preLoaderRoute: typeof LocaleProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$locale/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500Route: R500Route,
  ArchiveRoute: ArchiveRoute,
  BlogSlugRoute: BlogSlugRoute,
  LlmsTxtRoute: LlmsTxtRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  RssXmlRoute: RssXmlRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  TagsTagRoute: TagsTagRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleProjectsSlugRoute: LocaleProjectsSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleProjectsIndexRoute: LocaleProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
